name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Docker and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        id: buildAndPushImage
        uses: MaximilianoBz/dockerhub-buildpush@v1.0
        with:
          registry_url: 'docker.io'
          repository_name: 'helloworld'
          user_name: g0nzzza
          password: ${{ secrets.REGISTRY_PASSWORD }}
          image_version: 'v1.0'
          docker_file: '.'
      - name: Get pre step result output image_pull_url
        run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"

      # Checkout the other repository (the one with the YAML manifest)
      - name: Checkout other repository
        uses: actions/checkout@v3
        with:
          repository: gundicode/argocd-example-apps
          #token: ${{ secrets.REGISTRY_PASSWORD }}
          path: argocd-example-apps

      # Update the manifest file with the new Docker image tag
      - name: Update manifest
        run: |
          cd argocd-example-apps
          sed -i 's|image: g0nzzza/guestbook:.*|image: g0nzzza/guestbook:'"$GIT_SHA"'|g' guestbook/guestbook-ui-deployment.yaml
          cat guestbook/guestbook-ui-deployment.yaml

      # Commit and push changes to the other repository
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add guestbook/guestbook-ui-deployment.yaml
          git commit -m "Update image tag to $GIT_SHA"
          git push origin main
